[tool.autopep8]
max_line_length = 88

[tool.isort]
line_length = 88

# Pylance вроде бы должен учитывать это
[tool.pyright]
extraPaths = ["/opt/airflow/plugins"]
reportTypedDictNotRequiredAccess = "none"
reportUnusedExpression = "none"
exclude = [
    "**/__pycache__",
    "**/logs/**",
    "**/.devcontainer/.vscode-server",
    "**/.devcontainer/cache",
]

[tool.ruff]
line-length = 88
exclude = [
    "**/__pycache__",
    "**/logs/**",
    "**/.devcontainer/.vscode-server",
    "**/.devcontainer/cache",
]